// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Models;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20220714193952_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("app.Models.Product", b =>
                {
                    b.Property<int>("ProductCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ProductCode");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductCode = 82621,
                            Description = "کیفیت خوب، قیمت مناسب و ضمانت مرجوع و یا تعویض سایز یک هفته‌ای",
                            ImageName = "images/82621.jpg",
                            Name = "بوت بوفالو",
                            Price = 285000f
                        },
                        new
                        {
                            ProductCode = 45246,
                            Description = "کیفیت خوب، قیمت مناسب و ضمانت مرجوع و یا تعویض سایز یک هفته‌ای",
                            ImageName = "images/45246.jpg",
                            Name = "ونس",
                            Price = 220000f
                        },
                        new
                        {
                            ProductCode = 62183,
                            Description = "کیفیت خوب، قیمت مناسب و ضمانت مرجوع و یا تعویض سایز یک هفته‌ای",
                            ImageName = "images/62183.jpg",
                            Name = "ایرجردن وان",
                            Price = 360000f
                        },
                        new
                        {
                            ProductCode = 87239,
                            Description = "کیفیت خوب، قیمت مناسب و ضمانت مرجوع و یا تعویض سایز یک هفته‌ای",
                            ImageName = "images/87239.jpg",
                            Name = "نایک",
                            Price = 250000f
                        },
                        new
                        {
                            ProductCode = 94850,
                            Description = "کیفیت خوب، قیمت مناسب و ضمانت مرجوع و یا تعویض سایز یک هفته‌ای",
                            ImageName = "images/94850.jpg",
                            Name = "کالج پازلی",
                            Price = 180000f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
