// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Models;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("app.Models.College", b =>
                {
                    b.Property<byte>("ClgID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clgname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pname")
                        .HasColumnType("TEXT");

                    b.HasKey("ClgID");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            ClgID = (byte)1,
                            City = "تهران",
                            Clgname = "کامپیوتر",
                            Pname = "حسنی"
                        },
                        new
                        {
                            ClgID = (byte)2,
                            City = "خرم آباد",
                            Clgname = "حقوق",
                            Pname = "ناصری"
                        });
                });

            modelBuilder.Entity("app.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("ClgID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentID");

                    b.HasIndex("ClgID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 9711,
                            City = "شیراز",
                            ClgID = (byte)1,
                            GPA = 18.24f,
                            Name = "علی",
                            Surname = "علوی"
                        },
                        new
                        {
                            StudentID = 9833,
                            City = "کاشان",
                            ClgID = (byte)2,
                            GPA = 15.97f,
                            Name = "رضا",
                            Surname = "فرزامی"
                        },
                        new
                        {
                            StudentID = 9900,
                            City = "یزد",
                            ClgID = (byte)1,
                            GPA = 16.77f,
                            Name = "فاطمه",
                            Surname = "صادقی"
                        });
                });

            modelBuilder.Entity("app.Models.Student", b =>
                {
                    b.HasOne("app.Models.College", "College")
                        .WithMany("Students")
                        .HasForeignKey("ClgID");

                    b.Navigation("College");
                });

            modelBuilder.Entity("app.Models.College", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
